$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: diabetes-endpoint-crimson
model: azureml:diabetes-prod-model:1
code_configuration:
  code: .
  scoring_script: score.py
environment: azureml:diabetes-env:1
instance_type: Standard_F2s_v2
instance_count: 1
